"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONTROL_ACCOUNT_TAGS = exports.SYSTEM_ACCOUNT_TAGS = exports.DEFAULT_CHART_OF_ACCOUNTS = void 0;
const enums_1 = require("./enums");
exports.DEFAULT_CHART_OF_ACCOUNTS = [
    { code: '1000', name: 'Petty Cash', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CASH_AND_BANK, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1010', name: 'Business Checking Account', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CASH_AND_BANK, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1020', name: 'Business Savings Account', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CASH_AND_BANK, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1050', name: 'Undeposited Funds', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CASH_AND_BANK, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: true, isContra: false, systemTag: 'UNDEPOSITED_FUNDS' },
    { code: '1100', name: 'Accounts Receivable', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.ACCOUNTS_RECEIVABLE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: true, isContra: false, systemTag: 'AR' },
    { code: '1200', name: 'Prepaid Expenses', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CURRENT_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1210', name: 'Employee Advances', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CURRENT_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1250', name: 'Input Tax / Tax Receivable', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.CURRENT_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: true, isContra: false, systemTag: 'TAX_RECEIVABLE' },
    { code: '1300', name: 'Inventory Asset', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.INVENTORY, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: true, isContra: false, systemTag: 'INVENTORY' },
    { code: '1310', name: 'Goods Received Not Invoiced', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.INVENTORY, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: true, isContra: false, systemTag: 'GRNI' },
    { code: '1500', name: 'Furniture & Equipment', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.FIXED_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1510', name: 'Vehicles', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.FIXED_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1520', name: 'Computer Equipment', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.FIXED_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1550', name: 'Leasehold Improvements', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.FIXED_ASSET, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '1600', name: 'Accumulated Depreciation', type: enums_1.AccountType.ASSET, subType: enums_1.AccountSubType.FIXED_ASSET, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: true, systemTag: 'ACCUM_DEPRECIATION' },
    { code: '2000', name: 'Accounts Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.ACCOUNTS_PAYABLE, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: true, isContra: false, systemTag: 'AP' },
    { code: '2100', name: 'Sales Tax Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: true, isContra: false, systemTag: 'TAX_PAYABLE' },
    { code: '2110', name: 'Payroll Tax Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2120', name: 'Employee Benefits Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2130', name: 'Wages Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2150', name: 'Accrued Liabilities', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2160', name: 'Employee Reimbursement Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2170', name: 'Unearned Revenue', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CURRENT_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2200', name: 'Credit Card Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.CREDIT_CARD, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false, systemTag: 'CREDIT_CARD' },
    { code: '2500', name: 'Bank Loan', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.LONG_TERM_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '2510', name: 'Mortgage Payable', type: enums_1.AccountType.LIABILITY, subType: enums_1.AccountSubType.LONG_TERM_LIABILITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '3000', name: 'Owner\'s Equity / Share Capital', type: enums_1.AccountType.EQUITY, subType: enums_1.AccountSubType.OWNERS_EQUITY, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '3100', name: 'Owner\'s Draws', type: enums_1.AccountType.EQUITY, subType: enums_1.AccountSubType.OWNERS_EQUITY, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: true },
    { code: '3200', name: 'Retained Earnings', type: enums_1.AccountType.EQUITY, subType: enums_1.AccountSubType.RETAINED_EARNINGS, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: true, isContra: false, systemTag: 'RETAINED_EARNINGS' },
    { code: '3300', name: 'Opening Balance Equity', type: enums_1.AccountType.EQUITY, subType: enums_1.AccountSubType.OPENING_BALANCE, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: true, isContra: false, systemTag: 'OPENING_BALANCE_EQUITY' },
    { code: '4000', name: 'Sales Revenue', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.SALES_REVENUE, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '4010', name: 'Service Revenue', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.SALES_REVENUE, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '4020', name: 'Project Revenue', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.SALES_REVENUE, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '4050', name: 'Sales Discounts', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.SALES_REVENUE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: true },
    { code: '4060', name: 'Sales Returns & Allowances', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.SALES_REVENUE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: true },
    { code: '4500', name: 'Interest Income', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.OTHER_INCOME, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '4510', name: 'Other Income', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.OTHER_INCOME, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '4520', name: 'Realized FX Gain', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.OTHER_INCOME, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false, systemTag: 'FX_GAIN' },
    { code: '4530', name: 'Unrealized FX Gain', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.OTHER_INCOME, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '4540', name: 'Gain on Asset Disposal', type: enums_1.AccountType.INCOME, subType: enums_1.AccountSubType.OTHER_INCOME, normalBalance: enums_1.NormalBalance.CREDIT, isSystem: false, isContra: false },
    { code: '5000', name: 'Cost of Goods Sold', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.COST_OF_GOODS_SOLD, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'COGS' },
    { code: '5010', name: 'Cost of Services', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.COST_OF_GOODS_SOLD, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '5050', name: 'Inventory Adjustment', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.COST_OF_GOODS_SOLD, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'INVENTORY_ADJUSTMENT' },
    { code: '6000', name: 'Advertising & Marketing', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6010', name: 'Automobile Expense', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6020', name: 'Bank Fees & Charges', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'BANK_FEES' },
    { code: '6030', name: 'Depreciation Expense', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'DEPRECIATION' },
    { code: '6040', name: 'Insurance', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6050', name: 'Legal & Professional Fees', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6060', name: 'Office Supplies', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6070', name: 'Rent Expense', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6080', name: 'Repairs & Maintenance', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6090', name: 'Software & Subscriptions', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6100', name: 'Telephone & Internet', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6110', name: 'Travel Expense', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6120', name: 'Utilities', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6130', name: 'Meals & Entertainment', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6140', name: 'Postage & Shipping', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6150', name: 'Training & Education', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6160', name: 'Miscellaneous Expense', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6200', name: 'Bad Debt Expense', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OPERATING_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'BAD_DEBT' },
    { code: '6300', name: 'Wages & Salaries', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.PAYROLL_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6310', name: 'Employer Payroll Taxes', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.PAYROLL_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6320', name: 'Employee Benefits', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.PAYROLL_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6330', name: 'Contract Labor', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.PAYROLL_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6500', name: 'FX Loss', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OTHER_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'FX_LOSS' },
    { code: '6510', name: 'Loss on Asset Disposal', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OTHER_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6520', name: 'Penalties & Fines', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OTHER_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false },
    { code: '6600', name: 'Rounding Adjustment', type: enums_1.AccountType.EXPENSE, subType: enums_1.AccountSubType.OTHER_EXPENSE, normalBalance: enums_1.NormalBalance.DEBIT, isSystem: false, isContra: false, systemTag: 'ROUNDING' },
];
exports.SYSTEM_ACCOUNT_TAGS = {
    AR: 'AR',
    AP: 'AP',
    TAX_PAYABLE: 'TAX_PAYABLE',
    TAX_RECEIVABLE: 'TAX_RECEIVABLE',
    INVENTORY: 'INVENTORY',
    GRNI: 'GRNI',
    COGS: 'COGS',
    RETAINED_EARNINGS: 'RETAINED_EARNINGS',
    OPENING_BALANCE_EQUITY: 'OPENING_BALANCE_EQUITY',
    UNDEPOSITED_FUNDS: 'UNDEPOSITED_FUNDS',
    BANK_FEES: 'BANK_FEES',
    ACCUM_DEPRECIATION: 'ACCUM_DEPRECIATION',
    DEPRECIATION: 'DEPRECIATION',
    FX_GAIN: 'FX_GAIN',
    FX_LOSS: 'FX_LOSS',
    BAD_DEBT: 'BAD_DEBT',
    INVENTORY_ADJUSTMENT: 'INVENTORY_ADJUSTMENT',
    ROUNDING: 'ROUNDING',
    CREDIT_CARD: 'CREDIT_CARD',
};
exports.CONTROL_ACCOUNT_TAGS = new Set([
    exports.SYSTEM_ACCOUNT_TAGS.AR,
    exports.SYSTEM_ACCOUNT_TAGS.AP,
    exports.SYSTEM_ACCOUNT_TAGS.TAX_PAYABLE,
    exports.SYSTEM_ACCOUNT_TAGS.TAX_RECEIVABLE,
    exports.SYSTEM_ACCOUNT_TAGS.INVENTORY,
    exports.SYSTEM_ACCOUNT_TAGS.GRNI,
    exports.SYSTEM_ACCOUNT_TAGS.RETAINED_EARNINGS,
    exports.SYSTEM_ACCOUNT_TAGS.OPENING_BALANCE_EQUITY,
]);
//# sourceMappingURL=constants.js.map